### ISSUE TITLE
Our Requests Section

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#10]
## Description

Create "Our Request" section according to [Figma Designs](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3%3A1346&t=nJjv14L70ndKrLV5-0)

<img width="808" alt="image" src="https://user-images.githubusercontent.com/61670566/220216182-02d6b51a-daee-439c-85eb-2496cc4309d9.png">

## Learning Objectives

- React components 
- Tailwind CSS

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] Create `DropDownCard.tsx` component in components folder 
- [ ] Add our request static information to info folder 
- [ ] Create `OurRequest.tsx` section in sections folder, render corresponding information

## Useful Links

- [Figma Designs](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3%3A1346&t=nJjv14L70ndKrLV5-0)
- [Tailwind CSS Cheatsheet](https://tailwindcomponents.com/cheatsheet/)
