### ISSUE TITLE
Update Email Preference Procedure

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#105]
## Description

Admins will be able to update who should receive an email upon a data review request. This should be recorded in a `shouldEmail` field in [User Model](https://github.com/toriis-portal/toriis/blob/main/prisma/schema.prisma#L99). In this issue, write a tRPC procedure that 
- Takes in an array of user ids 
- Update the `shoulEmail` status of the user to be either true or false 

## Learning Objectives

- tRPC procedures with Prisma

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] Update the Prisma model to contain a `shouldEmail` field 
- [ ] Write the tRPC query `updateUserEmailPreference` 
  - Discuss approach with @zorazrr 
- [ ] Connect to frontend and test it with `useMutation` 

## Useful Links

- [The schema you are looking at](https://github.com/toriis-portal/toriis/blob/main/prisma/schema.prisma#L99)
- [useMutation in tRPC](https://trpc.io/docs/reactjs/usemutation)
- [CRUD operations in Prisma](https://www.prisma.io/docs/concepts/components/prisma-client/crud)

**Comment by masgras2** [comment]
Done in PR #115
