### ISSUE TITLE
Institutional Divestment Text Section

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#11]
## Description

Create Institutional Divestment lists section according to [Figma Design](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=179%3A270&t=dNLdQczcKAhNGwaS-0).

<img width="960" alt="image" src="https://user-images.githubusercontent.com/90807954/221061190-dbeb956f-83db-4dfa-950c-b417750db66b.png">

## Learning Objectives

- Tailwind CSS
- React Components 

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [x] Store listed information as a json object in [info folder](https://github.com/toriis-portal/toriis/tree/main/src/info)
- [x] Create a `ListItem.tsx` component in [components folder](https://github.com/toriis-portal/toriis/tree/main/src/components)
- [x] Render the item list in `InstitutionalDivestment` section in [sections folder](https://github.com/toriis-portal/toriis/tree/main/src/sections)

## Useful Links

- [Tailwind CSS Boxshadow](https://tailwindcss.com/docs/box-shadow)
