### ISSUE TITLE
What 1.5°C Means Section Accordion + Link Display 

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#128]
## Description

A section for displaying links! There is existing component and content type on Contentful, but we want to adjust those and make them more flexible. 

![image](https://user-images.githubusercontent.com/61670566/232314779-61613366-8d57-4bac-9ea7-ec388c32637c.png)

## Learning Objectives

- Contentful
- Tailwind CSS
- React 

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] Retrieve corresponding content on Contentful to this page 
  - Check with @zorazrr on this one 
- [ ] Extract the [Existing Link Display Section](https://github.com/toriis-portal/toriis/blob/main/src/sections/home/InstitutionalDivestments.tsx#L35) into a reusable component 
- [ ] Make the [Existing Company Details Accordion](https://github.com/toriis-portal/toriis/blob/main/src/components/Accordions/CompanyDetailsAccordion.tsx) more extensible 
- [ ] Put those two together! 

## Useful Links

- [Figma Designs](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3-1243&t=LiisXUgQRg8dB3Sg-0)
