### ISSUE TITLE
School/Institution List 

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#129]
## Description

Sections that display which institutions and schools have divested from fossil fuel. 

![image](https://user-images.githubusercontent.com/61670566/232314961-c95601a5-b94c-4194-a126-c91ee3fb4e29.png)

## Learning Objectives

- Contentful
- Tailwind CSS 
- React

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] Create corresponding content type on Contentful 
  - Potentially: `DivestedEntities: { name: string, type: SCHOOL | INSTITUTION }` (idk what to name this honestly) 
- [ ] Make a component (again idk what to name the component) to display the 
  - Make this component flexible ideally (we can adjust how many rows and columns to display per page) 
- [ ] Throw the component on fossil fuel page  

## Useful Links

- [List of Schools and Institutions that have Divested](https://docs.google.com/document/d/1tuS_vc-N1YQi29VLLZ9io3uynjwqD442MCSpT93de2c/edit?disco=AAAAu2NTvKQ)
- [Figma Designs](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3-1243&t=LiisXUgQRg8dB3Sg-0)
