### ISSUE TITLE
Interactive Treemap for Fossil Fuel Page

### ISSUE THREAD

**Issue by kennykos** [toriis-portal/toriis#174]
## Description

Currently, the Fossil Fuel page has a static Treemap 
![image](https://user-images.githubusercontent.com/73120774/235823238-235b4a27-7bf2-430e-963b-b6dda115f797.png)

But we want an interactive Treemap like so
![image](https://user-images.githubusercontent.com/73120774/235823287-b9d806f7-84cd-4404-aa4f-e1a8c9bcbaf2.png)
https://apexcharts.com/javascript-chart-demos/treemap-charts/treemap-multiple-series/

There will be three dimensions: carbon underground 200 (red), fossil fuel (orange), and rest of the portfolio (blue)
Additionally, we should have each block open the corresponding tare page when clicked.

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [x] Create multidimensional tree chart that relies on DB queries
- [ ] Link to Fossil Fuel Page
- [x] Format each dimension as carbon underground 200 (red), fossil fuel (orange), and rest of the portfolio (blue)
- [ ] Display the company name on the chart and hover over amount of CO2, with the legend enabled
- [ ] On click, send to corresponding tare page
- [ ] Make sure it looks good in page

## Useful Links

- https://apexcharts.com/javascript-chart-demos/treemap-charts/treemap-multiple-series/
- https://www.toriis.earth/fossil-fuel
