### ISSUE TITLE
Toggle Between Financed Emissions & Net Asset Value Treemaps

### ISSUE THREAD

**Issue by kennykos** [toriis-portal/toriis#179]
## Description

Implement the ability to toggle between Financed Emissions and Net Asset Value Treemaps

![image](https://github.com/toriis-portal/toriis/assets/73120774/fedf85a5-bf7a-4849-832a-a1c55b460d6f)

## Todo

- [x] Get series for both Financed Emissions & Net Asset Value
- [x] Break Series down by fossil fuel classification and sector
- [x] Implement Button Toggles as per the Figma Above
- [x] Check that tool-tips are correct for both series
- [x] Add button description dropdown 

### Extra Credit

- [x] Make the title names cleaner (right now they are ugly and too technical) 
- [x] Check with design professional on dimensions of the chart (@faithlos)
- [ ] Check with design professional on size of company title       (@faithlos)
- [ ] Clicking a sector zooms into a treemap of sector                    (@faithlos can we get a design so this is clickable?)
- [ ] Hovering over sector name triggers toottip that gives the percentage breakdown of the given sector
- [ ] Check with design professional on size of company title       (@faithlos)
- [ ] Clicking a sector zooms into a treemap of sector                    (@faithlos can we get a design so this is clickable?)
- [ ] Hovering over sector name triggers toottip that gives the percentage breakdown of the given sector 
- [x] Have back button work when clicked from treemap
