### ISSUE TITLE
Switch to RichText for Schools and Institutions Divested lists

### ISSUE THREAD

**Issue by kennykos** [toriis-portal/toriis#182]
## Description

Currently, the schools and institutions divested lists are in plaintext, which means we can not link to external sites. Because these lists are on confluentful, we need to add a new richtext field for both these lists, add the links, then reconfigure the code to display richtext links while maintaining the page formatting. 

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [x] Create richtext fields in contentful
- [x] update code to integrate richtext
- [x] add the links in contentful
- [x] add footnotes to contentful
- [x] integrate footnotes into repo
- [ ] delete old fields from contentful
