### ISSUE TITLE
Refute UIS Response Section 

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#19]
## Description

Refer to [Figma](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3%3A1346&t=vI8rBgLgp7N3nF9i-0).

![image](https://user-images.githubusercontent.com/61670566/220524456-781e3c74-9b54-4f18-b691-33d6e1db9d80.png)

## Learning Objectives

- React components 
- Tailwind CSS

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] Build the Carousel component `Carousel.tsx` in components folder 
  - Because this requires a lot of customization, building it from scratch might be good 
  - But also feel free to explore existing components potentially! 
- [ ] Create a `RefuteUISResponse.tsx` section in sections folder 
- [ ] Add text segment to json file and render in the section 

## Useful Links

- [Tailwind Carousel Examples](https://tailwind-elements.com/docs/standard/components/carousel/)
- [Hero Icons](https://heroicons.com/)
