### ISSUE TITLE
Sign the Letter

### ISSUE THREAD

**Issue by kennykos** [toriis-portal/toriis#192]
## Description

The Sign the Letter section of the Take Action page is the biggest feature, as it will bring completely new functionality to toriis. We will have separate input fields and a button that will parse the inputs into the DB when all the fields are full. Additionally, we will add a counter to the open letter section of how many signatories are in our database. All in all, here is what our Take Action page will look like at the end of this Issue

![Image](https://github.com/toriis-portal/toriis/assets/73120774/57935807-8102-4063-8886-ad5d3e4577e4)

## Todo

- [x] Implement the Sign the Letter Subsection
- [x] Implement nav bar for the Take Action Page
- [ ] Implement the signatories counter and Sign the Letter button in the Open Letter Section

**Comment by lizageorge** [comment]
Here's a possible adjusted breakdown of tasks:
- [ ] Implement nav bar for Take Acton Page
- [ ] Implement the Sign the Letter Subsection
- [ ] Implement Sign the Letter button in the Open Letter Section
- [ ] Add form to Sign the Letter subsection
- [ ] Implement signatories counter (connected to DB)
- [ ] Connect form to DB (with corresponding validations)
