### ISSUE TITLE
Top-Level Nav Bar Component

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#2]
## Description

Create a navigation bar as displayed in [Figma](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=80%3A10&t=AdTsHy93OyN1rx1Q-0). Clicking on each nav item should bring user to the corresponding pages. 

![image](https://user-images.githubusercontent.com/61670566/219433084-baa7d3d1-2760-4577-897f-1e0eedf7026d.png)

## Learning Objectives 

- NextJs
- Tailwind CSS
- React Components

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] Create `NavButton.tsx` in [components](https://github.com/toriis-portal/toriis/tree/main/src/components) folder 
- [ ] Create `NavBar.tsx` in [components](https://github.com/toriis-portal/toriis/tree/main/src/components) folder that includes the NavButtons and logo 
- [ ] Display the Nav Bar component on all pages 

## Useful Links

- [Figma Design](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=80%3A10&t=AdTsHy93OyN1rx1Q-0)
- [NextJs Link Component](https://nextjs.org/learn/basics/navigate-between-pages/link-component)
- [A Guide to CSS Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)
- [Tailwind CSS Cheatsheet](https://tailwindcomponents.com/cheatsheet/)

## Timeline 

2 dev nights
