### ISSUE TITLE
Change Refute UIS Response to Responding to Pushback and Update Style

### ISSUE THREAD

**Issue by kennykos** [toriis-portal/toriis#202]
## Description

Rename the Refute UIS Response section to Responding to Pushback and implement small style changes to the Card Carousel. 

![Image](https://github.com/toriis-portal/toriis/assets/73120774/cd322507-385d-4a08-9d36-c8082a39bb25)

## Todo

- [x] Rename section to Responding to Pushback
- [x] Update contentful to accommodate style changes
- [x] Implement claim/response style changes
