### ISSUE TITLE
Select Investment Database by year

### ISSUE THREAD

**Issue by kennykos** [toriis-portal/toriis#206]
## Description

Medium updated to the Learn About Investments page including renaming the page and allowing for selection by fiscal year.

![Image](https://github.com/toriis-portal/toriis/assets/73120774/5beca8bc-01e6-44ab-a812-17d7a64d14d9)

![Image](https://github.com/toriis-portal/toriis/assets/73120774/7c24eca2-6724-4fea-a3ec-78735a7a13db)

## Learning Objectives

- Objective 1

## Todo

- [x] Rename Learn About Investments page to Investment Database
- [x] Update Primary Nav Bar with name change
- [ ] Change Title and add dropdown component
- [ ] Update query to select by year
- [ ] Update investment details on tare page to only display investments from the year selected
