### ISSUE TITLE
Continue the Momentum Section

### ISSUE THREAD

**Issue by kennykos** [toriis-portal/toriis#215]
## Description

Implement the Continue the Momentum Section and List, and integrate into contentful.

![Image](https://github.com/toriis-portal/toriis/assets/73120774/b311b0b6-a3ef-4957-940e-0011d304b005)

## Todo

- [ ] Create Continue the Momentum section
- [ ] Add Continue the Momentum to nav bar
- [ ] Integrate into contentful
