### ISSUE TITLE
Optimize Donut Chart + Tree Chart Data Retrieval

### ISSUE THREAD

**Issue by eeshabarua** [toriis-portal/toriis#237]
## Description

Currently, the donut chart and tree chart components run a tRPC procedure on every reload, which can lead to performance issues. Optimize the data using a MongoDB aggregation or stored procedure.

## Learning Objectives

- Understand the current aggregation pipeline (MongoDB doesn't have stored procedures)
- Weigh the benefits of Response Caching to speed up retrieval on reload / rerender

## Todo

- [ ] View MongoDB cluster
- [ ] Donut chart caching / stored procedure
- [ ] Tree chart caching / stored procedure

## Useful Links

- https://www.mongodb.com/basics/aggregation
- https://trpc.io/docs/server/caching
- https://www.mongodb.com/features/stored-procedures

**Comment by kennykos** [comment]
We should use [mongodb triggers](https://www.mongodb.com/features/database-triggers) instead of a stored procedure. The trigger should execute every time the the relevant collections in the production DB is updated. 

Also, it would be nice if we could store these triggers in the repository instead of mongo's website so we could have nice version control and peer review, but that isn't a deal breaker.
