### ISSUE TITLE
Company Card 

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#35]
## Description

Company card to display overview of company information on Investments page. 

<img width="632" alt="image" src="https://user-images.githubusercontent.com/61670566/222603699-94a08df0-fa9e-422f-9ec3-98adfb0f3b4c.png">

## Learning Objectives

- React
- Tailwind CSS 

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] Create necessary `tag` components that goes into the card
- [ ] Create the `CompanyCard` component, use Flexbox! 
- [ ] Integrate it with the query on `investment` page 
- [ ] Clicking on the company card should bring users to company details page 

## Useful Links

- [Figma Design](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3%3A1346&t=lnuUvvQYHf36ezuc-0)
- [A Complete Guide to Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

## Timeline 
By end of Thursday
