### ISSUE TITLE
Company Name Search

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#38]
## Description

Users should be able to search up a company by its name. Note that we want 
- **backend search**, meaning the searching of the database will happen on the server rather than client side 

![image](https://user-images.githubusercontent.com/61670566/223629425-e2a3bf84-e7e0-4cc4-a89c-35650b6d32e5.png)

## Learning Objectives

- React Query
- tRPC 
- Tailwind CSS

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [x] Add a string search input to the existing [companyRouter](https://github.com/toriis-portal/toriis/blob/main/src/server/api/routers/company.ts) and return filtered results 
- [x] Add an input box component to Investments page 
- [x] Handle situation of "No results found"
