### ISSUE TITLE
Infinite Query to Get Investment Data 

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#4]
## Description

Create a tRPC query to get investment table data, joined with company table (paginated, with `limit`) and fetch it on the frontend. The expected behavior is: 
- By default, `limit` number of rows are rendered 
- After clicking on a "load more" button, an additional `limit` amount of rows will be rendered
Similar to [this website](https://fossilfreefunds.org/funds?pg=1&srt=ussif).

The final data should look like: 
```
{
  id: string/uuid,
  name: string, 
  sector: enum,
  industry: string, 
  environmental_grade: string // this is not here yet, dwai
  asset_sum: number
}
```

## Learning Objectives

- React Query
- tRPC

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [x] Set up new tRPC router `companyRouter` and procedure `getCompanies` in [routers](https://github.com/toriis-portal/toriis/tree/main/src/server/api/routers) folder 
- [x] Build the procedure to get investment data based on limit and cursor
- [ ] Join the company records with investment table, based on `companyId`, calculate net asset sum 
  - $\sum_{\text{all investments given company}}(\text{quantity} \times \text{market value})$
- [ ] Use `useInfiniteQuery` to fetch the data on the frontend, this could temporarily live in the `pages/investments/index.tsx` page
  - Do not worry too much about UI in this ticket! Will be addressed once designs are here. 

## Useful Links

- [UseInfiniteQuery Example](https://codesandbox.io/s/79xew?file=/src/App.js:86-102)
- [tRPC useInfiniteQuery](https://trpc.io/docs/useInfiniteQuery) 
- [Cursor Pagination in Prisma](https://www.prisma.io/docs/concepts/components/prisma-client/pagination)
- [Example of Infinite Query](https://daily-dev-tips.com/posts/infinite-loading-with-react-query/)
- [Prisma Relational Query](https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries)

## Timeline 

TBD
