### ISSUE TITLE
Filter Dropdowns with Backend Query

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#46]
## Description

Extend the dropdown selection component based on [Amit's dropdown](https://github.com/toriis-portal/toriis/blob/main/src/components/Selects/Select.tsx). 
- It already contains a lot of stuff 
- Just needs more tweaks plus backend fiilters 

You do need to worry about backend query in this issue. 

![image](https://user-images.githubusercontent.com/61670566/223628416-f8c8ce67-e7db-4627-af7c-4b8b290801a7.png)

## Learning Objectives

- Tailwind CSS
- tRPC 
- Prisma Queries 
- MongoDB 

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [x] Extend [Amit's dropdown](https://github.com/toriis-portal/toriis/blob/main/src/components/Selects/Select.tsx) component to fit the four selection styles 
- [x] For each dropdown, pass in corresponding data and display on 'Investment' page 
  - May need a backend query to get all unique `industry` values) 
  - Should create an enum for environment grade 
- [ ] Add corresponding backend filters to [CompanyRouter](https://github.com/toriis-portal/toriis/blob/main/src/server/api/routers/company.ts)

## Useful Links

- [Figma Design](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3%3A1346&t=K1OhAkHupD40kbLM-0)
- [Prisma Filtering and Sorting](https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting)
