### ISSUE TITLE
Investment Details Table Frontend

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#52]
## Description

Create a table with Load More functionality. Frontend only! Pass in dummy data and you do not need to worry about backend query in this issue. 

![image](https://user-images.githubusercontent.com/61670566/223633823-d590a0fd-0302-4763-a75f-a3978c109970.png)

## Learning Objectives

- Tailwind CSS 
- React Components

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [x] Create a `Row.tsx` component that takes in a `Investment` as input 
- [x] Create a `Investment Table` component that uses `Row.tsx` to render multiple investments 
- [x] When "Load More" button is clicked, more rows should be rendered 
- [x] Pass in dummy data to test the table
