### ISSUE TITLE
Secondary Sticky Nav Bar with Anchor and Scroll

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#6]
## Description

A Navigation Bar that sticks on the top and navigates users to different sections on the page.

![image](https://user-images.githubusercontent.com/61670566/219870667-9a6c99a1-f053-4a94-93ba-e73e816aa76b.png)

## Learning Objectives

- React-Scroll
- Tailwind CSS (lots of CSS!) 

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] Create a Nav Bar component with for the home page. Note that: 
  - Nav items should be "active" when a section is in viewport 
  - Clicking on the item will bring users to a section on page, there should be scroll animations
  - [React Scroll](https://github.com/fisshy/react-scroll) is recommended, but feel free to explore other methods!
- [ ] Style the Nav Bar component to match [Figma Design](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3%3A1243&t=94OBWIFhKXQRQRI3-0)
- [ ] Extract the Nav Bar component and make it adaptable to multiple pages 

Additional notes: this issue ticket will go concurrently with other tickets on building out the sections, so the sections may not be ready when you start this ticket, you should create temporary sections to test the functionality.

## Useful Links

- [Figma Design](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3%3A1243&t=94OBWIFhKXQRQRI3-0)
- [React Scroll](https://github.com/fisshy/react-scroll)
- [React Scroll Example Code Sandbox](https://codesandbox.io/s/basic-6t84k)
- [CSS Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

## Timeline 

By beginning of Monday dev night
