### ISSUE TITLE
Financial Case Accordion

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#67]
## Description

![image](https://user-images.githubusercontent.com/61670566/226363559-2e08eb48-c7cc-4a6b-b9a2-d918459a15be.png)

## Learning Objectives

- Contentful 
- Tailwind CSS 

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] Create a new Content Type `Case` in Contentful 
  - It should contain fields: 
    - Title: text
    - Details: rich text 
    - Url: link
  - Add entries to the new content type
- [ ] Create new accordion component to render the information 
- [ ] Put everything in Fossil Fuel page 

## Useful Links

- [Contentful Richtext Renderer](https://www.npmjs.com/package/@contentful/rich-text-react-renderer)
- Check how [home page](https://github.com/toriis-portal/toriis/blob/main/src/pages/home/index.tsx#L22) is using Contentful and the [setup of Contentful](https://github.com/toriis-portal/toriis/blob/main/src/utils/content.ts) 
- [Figma Designs](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3-1243&t=g8ctE0PkdalZpjxM-0)
- Check with @zorazrr to get an idea of how Contentful works here
