### ISSUE TITLE
Update Database to Include Bloomberg/CDP Data

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#69]
## Description

Update Database to Include Bloomberg Data
- CDP 
- Carbon Scope Emission
- Bloomberg ID for companies

## ToDos 

- [x] Update `Company` collection with updated ticker values 
- [x] Update `Company` collection with Bloomerg Id 
- [x] Add data to CDP collection 
- [x] Add data to Bloomerg collection 
- [x] Add corresponding schemas
