### ISSUE TITLE
Landing Section

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#8]
## Description

Create the landing section on the homepage, along with the donut chart. Refer to [Figma Design](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3%3A1346&t=vI8rBgLgp7N3nF9i-0).

![image](https://user-images.githubusercontent.com/61670566/220523155-2717a602-2db1-42a9-92de-a540c1095d86.png)

## Learning Objectives

- tRPC with Prisma aggregations 
- Apex Charts
- Tailwind CSS 

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [x] Add dependencies with `yarn add react-apexcharts apexcharts`
- [x] Create a new tRPC procedure that groups company data into the format of `{sector: string, count: number}`
- [ ] Render the aggregated data in a donut chart with Appex Charts 
- [ ] Create a landing section component 
  - Add #7 to the section 
  - Add static text information  

## Useful Links

- [Figma Design](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3%3A1346&t=vI8rBgLgp7N3nF9i-0)
- [Prisma GroupBy Query](https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing#group-by)
- [Official React Appexcharts Demo](https://apexcharts.com/react-chart-demos/)
- [Data Vis in React using Apexcharts](https://www.section.io/engineering-education/data-visualization-in-react-using-apexcharts/)
- [Charting with React Apexcharts](https://blog.logrocket.com/charting-react-apexcharts/)
