### ISSUE TITLE
Scope Emission Visualization

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#81]
## Description

This Bar Chart displays the Green House Gas (GHG) scope emissions (scope 1-3) for companies. 

<img width="743" alt="image" src="https://user-images.githubusercontent.com/61670566/227738136-0a94ff88-a3f3-46ab-bd0a-f0c09496a80a.png">

The data we are focusing on looks like this (you might want to go into the DB for this one to get a better sense):

```
model Emission {
  id         String    @id @default(auto()) @map("_id") @db.ObjectId
  company    Company   @relation(fields: [companyId], references: [id], onDelete: Cascade)
  companyId  String    @unique @db.ObjectId
  date       DateTime?
  version    Int?
  scopeOne   Float?
  scopeTwo   Float?
  scopeThree Float?
}
```

## Learning Objectives

- tRPC with Prisma
- Apex Chart 
- Tailwind CSS

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] Create a tRPC procedure that gets all the scope emission information based on company 
- [ ] Create a `EmissionBarChart` component with Apex Chart that: 
  - Takes a company or company id and pass in the information to the tRPC procedure mentioned above 
  - Organize the received data and display with Apex Chart 
  - Notice that some fields may be missing from certain companies, so you may need to be careful in handling missing fields
- [ ] Handle rendering the chart on [Company Details Page](https://github.com/toriis-portal/toriis/blob/main/src/pages/company/%5Bid%5D.tsx)

## Useful Links

- [Apex Bar Chart](https://apexcharts.com/react-chart-demos/bar-charts/basic/)
- [Reading operations in Prisma](https://www.prisma.io/docs/concepts/components/prisma-client/crud#read)
- [tRPC useQuery](https://trpc.io/docs/reactjs/usequery)

**Comment by zorazrr** [comment]
Resolved in #101
