### ISSUE TITLE
Fossil Fuel RadialBar Chart

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#82]
## Description

This RadialBar Chart displays the fuel consumption information for companies based on data from Bloomberg database.

![image](https://user-images.githubusercontent.com/61670566/227947315-3942bb21-b66e-4a63-b89e-30ce4ead9b9e.png)

The data we are focusing on looks like this (you might want to go into the DB for this one to get a better sense):
```
model Fuel {
  id                 String  @id @default(auto()) @map("_id") @db.ObjectId
  company            Company @relation(fields: [companyId], references: [id], onDelete: Cascade)
  companyId          String  @unique @db.ObjectId
  year               Int
  totalConsumption   Float?
  biodiesels         Float?
  biogases           Float?
  crudeOil           Float?
  coal               Float?
  oil                Float?
  gas                Float?
  otherBiomass       Float?
  sustainableBiomass Float?
  otherRenewable     Float?
  otherNonRenewable  Float?
}
```

## Learning Objectives

- tRPC with Prisma
- Apex Chart 
- Tailwind CSS

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] In the `getCompany` procedure, include fossil fuel information 
- [ ] Create a `FuelRadialChart` component with Apex Chart that: 
  - Takes the fuel information
  - Organize the received data and display with Apex Chart 
  - Notice that some fields may be missing from certain companies, so you may need to be careful in handling missing fields
- [ ] Handle rendering the chart on [Company Details Page](https://github.com/toriis-portal/toriis/blob/main/src/pages/company/%5Bid%5D.tsx)

## Useful Links

- [Apex RadialBar Chart](https://apexcharts.com/javascript-chart-demos/radialbar-charts/multiple-radialbars/)
- [Reading operations in Prisma](https://www.prisma.io/docs/concepts/components/prisma-client/crud#read)
- [tRPC useQuery](https://trpc.io/docs/reactjs/usequery)
