### ISSUE TITLE
Energy RadialBar Chart

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#84]
## Description

This RadialBar Chart displays the energy consumption information for companies based on data from Bloomberg terminal.

![image](https://user-images.githubusercontent.com/61670566/227975059-bc46745d-20cb-4b5f-a28b-26ccc79ea305.png)
The data we are focusing on looks like this (you might want to go into the DB for this one to get a better sense):
```
model Energy {
  id                           String  @id @default(auto()) @map("_id") @db.ObjectId
  company                      Company @relation(fields: [companyId], references: [id], onDelete: Cascade)
  companyId                    String  @unique @db.ObjectId
  year                         Int?
  totalConsumption             Float?
  totalRenewableConsumption    Float?
  totalNonRenewableConsumption Float?
}
```

## Learning Objectives

- tRPC with Prisma
- Apex Chart 
- Tailwind CSS

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] Create a tRPC procedure that gets all the energy information based on company 
- [ ] Create a `EnergyRadialChart` component with Apex Chart that: 
  - Takes a company or company id and pass in the information to the tRPC procedure mentioned above 
  - Organize the received data and display with Apex Chart 
  - Notice that some fields may be missing from certain companies, so you may need to be careful in handling missing fields
- [ ] Handle rendering the chart on [Company Details Page](https://github.com/toriis-portal/toriis/blob/main/src/pages/company/%5Bid%5D.tsx)

## Useful Links
- [Apex RadialBar Chart](https://apexcharts.com/react-chart-demos/radialbar-charts/basic/)
- [Reading operations in Prisma](https://www.prisma.io/docs/concepts/components/prisma-client/crud#read)
- [tRPC useQuery](https://trpc.io/docs/reactjs/usequery)
