### ISSUE TITLE
Passing in Dynamic Content to Tooltips 

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#88]
## Description

Currently the content in the tooltips is hard-coded, however, we want to render content based on company. That is, we need to fetch the corresponding descriptions for industry and sector specific to the one company displayed. See the following documents for details: 
- [Industry Descriptions](https://docs.google.com/spreadsheets/d/1bsP0OFUgsegq9m4l2mCsvHd_-EYxIaFp/edit#gid=1250584677)
- [Sector Descriptions](https://docs.google.com/document/d/1a5nMPrrGbCPA2aBGDms27uxIAZrJKgO-lov5svCJsdc/edit)

![image](https://user-images.githubusercontent.com/61670566/228264770-94c9dbd2-6296-4de8-8b55-6ed0f5609596.png)

## Learning Objectives

- Contentful
- tRPC
- React components 

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [x] Create new content types in Contentful for the information linked above and add entries into them 
  - Sector should have `Sector: {name : short text, details: long text}`
  - Industry should have `Industry: {name : short text, details: long text}`
- [ ] In [Company Details Page](https://github.com/toriis-portal/toriis/blob/main/src/pages/company/%5Bid%5D.tsx), after retrieving the company's industry and sector information, find corresponding entries in contentful and render the details accordingly 
  - There are roughly two ways to go about this, feel free to experiment with either one:
    1. In the `getCompany` tRPC procedure, establish connection to Contentful and return entries from the procedure (I'd say try this first), or
    2. Use `getServerSideProps` to fetch all entries and get corresponding entry on the frontend 
- [ ] When the industry/sector information is missing for a company, render "None specified"
- [ ] Display net asset value as a dynamic value as well 
  - Check `utils/helper` file for a helper function to convert numbers to strings

## Useful Links

- Check how [home page](https://github.com/toriis-portal/toriis/blob/main/src/pages/home/index.tsx#L22) is using Contentful and the [setup of Contentful](https://github.com/toriis-portal/toriis/blob/main/src/utils/content.ts) 
- Check with @zorazrr to get an idea of how Contentful works here
