### ISSUE TITLE
Invite Admin Bar

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#92]
## Description

This issue should take care of: 
- Rendering the frontend of the invite admin input 
- Adding the admin info (email) to the database `WhitelistedUser` 

<img width="754" alt="image" src="https://user-images.githubusercontent.com/61670566/229260363-98a8cc86-2b68-4195-aef4-28dfbb29c17b.png">

## Learning Objectives

- tRPC with Prisma 
- Tailwind CSS

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] Create a tRPC procedure `addWhitelistedUser` 
- [x] Make the frontend input component 
- [ ] Connect the two together and render on `/admin/management` page 

## Useful Links

- [Prisma Create](https://www.prisma.io/docs/concepts/components/prisma-client/crud#create)
