### ISSUE TITLE
Admin List Table with Edit Mode

### ISSUE THREAD

**Issue by zorazrr** [toriis-portal/toriis#94]
## Description

This table is a major part of the Admin Administration Management part, where admin will be able to view all users with admin permissions and edit the list accordingly. In this issue, you are only concerned with creating the frontend of the table + retrieving the list of admin users from the database. Do NOT worry about any mutations (add/delete) involved. 

<img width="744" alt="image" src="https://user-images.githubusercontent.com/61670566/229260458-53f0166d-02af-410e-8790-449e900d96c4.png">
<img width="770" alt="image" src="https://user-images.githubusercontent.com/61670566/229261253-aa668495-e894-41db-997e-7dddfb115c9d.png">

## Learning Objectives

- tRPC and React Query 
- Tailwind CSS 
- React Components

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] Create a `getAllUsers` procedure in `user` router to get all admins from DB 
- [ ] Use `useQuery` to get the list of admins on frontend (`/admin/management` page) 
- [ ] Create the table component to display the data 
- [ ] Add "edit mode" toggle to the table component 
- [ ] Manage the state of updated users

## Useful Links

- [useQuery in tRPC](https://trpc.io/docs/reactjs/usequery)
- [Figma Designs](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3-1346&t=lUBXrNC9znNIjdiE-0)
